test:
  stage: test
  image: mhart/alpine-node:12
  script:
    - yarn
    - npm run lint

deploy_production:
  stage: deploy
  image: docker
  tags:
    - production
  only:
    refs:
    - tags
    - triggers
    - master
  when: manual
  before_script:
    - export GOOGLE_MAPS_API_KEY="$GOOGLE_MAPS_API_KEY"
    - export SECRET_IV="$SECRET_IV"
    - export SECRET_KEY="$SECRET_KEY"
    - export SHOPIFY_URL="$SHOPIFY_URL"
    - export SHOPIFY_VARIANT_ID="$SHOPIFY_VARIANT_ID"
    - export STOREFRONT_API_KEY="$STOREFRONT_API_KEY"
  script:
    - docker build -t whenigrowup .
    - docker run --name web_whenigrowup -p 3000:80 -w /usr/src/wigu --expose 80 --expose 443 -e VIRTUAL_HOST=wigu.taufiqelrahman.com -e LETSENCRYPT_HOST=wigu.taufiqelrahman.com whenigrowup
