# test:
#   stage: test
#   image: mhart/alpine-node:12
#   script:
#     - yarn
#     - npm run lint

deploy_production:
  stage: deploy
  image: docker:stable
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  services:
    - docker:dind
  tags:
    - production
  only:
    refs:
    - tags
    - triggers
    - master
  when: manual
  before_script:
    - docker info
    - apk add --no-cache docker-compose
  script:
    - export >> .env
    - export >> /allgrownup/.env
    - docker-compose up --build -d
