test:
  stage: test
  image: mhart/alpine-node:12
  script:
    - yarn
    - npm run lint
    - npm run build

deploy_production:
  stage: deploy
  image: docker
  services:
    - docker:dind  
  tags:
    - production
  only:
    refs:
    - tags
    - triggers
    - master
  when: manual
  before_script:
    - export GOOGLE_MAPS_API_KEY="$GOOGLE_MAPS_API_KEY"
    - export SECRET_IV="$SECRET_IV"
    - export SECRET_KEY="$SECRET_KEY"
    - export SHOPIFY_URL="$SHOPIFY_URL"
    - export SHOPIFY_VARIANT_ID="$SHOPIFY_VARIANT_ID"
    - export STOREFRONT_API_KEY="$STOREFRONT_API_KEY"
  script:
    - docker-compose up -d
