# test:
#   stage: test
#   image: mhart/alpine-node:12
#   script:
#     - yarn
#     - npm run lint

deploy_production:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  tags:
    - production
  only:
    refs:
    - tags
    - triggers
    - master
  when: manual
  before_script:
    - docker info
    - apk add --no-cache docker-compose git
    - echo APP_URL="$APP_URL" >> .env
    - echo API_URL="$API_URL" >> .env
    - echo DOMAIN="$DOMAIN" >> .env
    - echo GOOGLE_MAPS_API_KEY="$GOOGLE_MAPS_API_KEY" >> .env
    - echo SECRET_IV="$SECRET_IV" >> .env
    - echo SECRET_KEY="$SECRET_KEY" >> .env
    - echo SHOPIFY_URL="$SHOPIFY_URL" >> .env
    - echo SHOPIFY_VARIANT_ID="$SHOPIFY_VARIANT_ID" >> .env
    - echo STOREFRONT_API_KEY="$STOREFRONT_API_KEY" >> .env
    - cat .env
  script:
    - source .env
    # - git submodule sync --recursive
    # - git submodule update --init --recursive
    # - cp .env ./allgrownup/.env
    - docker-compose up --build -d
    # - docker-compose up -d
