# test:
#   stage: test
#   image: mhart/alpine-node:12
#   script:
#     - yarn
#     - npm run lint
image: ubuntu:18.04

services:
  - docker
  - docker:dind

deploy_production:
  stage: deploy
  tags:
    - production
  only:
    refs:
    - tags
    - triggers
    - master
  when: manual
  script:
    - docker info
    # - apk add --no-cache git py-pip gcc
    # - sudo apt-get update
    # - sudo apt-get install docker-ce docker-ce-cli containerd.io
    - apt-get install -y python-pip
    # - yum install epel-release
    # - yum install python-pip
    - echo APP_URL="$APP_URL" >> .env
    - echo API_URL="$API_URL" >> .env
    - echo GA_TRACKING_ID="$GA_TRACKING_ID" >> .env
    - echo FACEBOOK_PIXEL_ID="$FACEBOOK_PIXEL_ID" >> .env
    - echo DOMAIN="$DOMAIN" >> .env
    - echo GOOGLE_MAPS_API_KEY="$GOOGLE_MAPS_API_KEY" >> .env
    - echo SECRET_IV="$SECRET_IV" >> .env
    - echo SECRET_KEY="$SECRET_KEY" >> .env
    - echo SHOPIFY_URL="$SHOPIFY_URL" >> .env
    - echo SHOPIFY_VARIANT_ID="$SHOPIFY_VARIANT_ID" >> .env
    - echo STOREFRONT_API_KEY="$STOREFRONT_API_KEY" >> .env
    - cat .env
    # - pip install python-dotenv
    - pip install docker-compose
  # script:
    - source .env
    # - git submodule sync --recursive
    # - git submodule update --init --recursive
    # - cp .env ./allgrownup/.env
    - docker-compose up --build -d
    # - docker-compose up -d
